-- 코드를 입력하세요
SELECT
    a.PRODUCT_CODE AS PRODUCT_CODE,
    SUM(a.PRICE * b.SALES_AMOUNT) AS SALES
FROM PRODUCT a, OFFLINE_SALE b
WHERE a.PRODUCT_ID = b.PRODUCT_ID
GROUP BY a.PRODUCT_CODE
ORDER BY SALES desc, PRODUCT_CODE;