-- 코드를 입력하세요
SELECT
    i.ANIMAL_ID AS ANIMAL_ID,
    i.ANIMAL_TYPE AS ANIMAL_TYPE,
    i.NAME AS NAME
FROM ANIMAL_INS i, ANIMAL_OUTS o
WHERE i.ANIMAL_ID = o.ANIMAL_ID
    AND i.SEX_UPON_INTAKE LIKE 'Intact%'
    AND o.SEX_UPON_OUTCOME NOT LIKE 'Intact%'
ORDER BY ANIMAL_ID;