-- 코드를 작성해주세요
WITH RECURSIVE r AS (
    SELECT ID, 1 as GENERATION
    FROM ECOLI_DATA e1
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT e2.ID, 1 + GENERATION
    FROM ECOLI_DATA e2
    JOIN r
    ON e2.PARENT_ID = r.ID
)

SELECT COUNT(*) AS COUNT, a.GENERATION AS GENERATION
FROM r a
JOIN ECOLI_DATA e
ON a.ID = e.ID
WHERE !EXISTS (
    SELECT 1 FROM ECOLI_DATA other WHERE a.ID = other.PARENT_ID
)
GROUP BY a.GENERATION
ORDER BY GENERATION;